### ISSUE TITLE
Support Argon hash passwords in the file

### ISSUE THREAD

**Issue by nogweii** [copiousfreetime/htauth#16]
Using the [argon2 gem](https://github.com/technion/ruby-argon2).

I intend to use the htauth gem to easily query an htpasswd formatted file but with modern password storage recommendations. What do you think of adding support for this algorithm?

It might also make more sense to build this as more as a pluggable library, so someone wanting to use it would need to depend on `htauth` and `htauth-argon` gems.

**Comment by copiousfreetime** [comment]
That should be doable -- my quick look is that its a new `$argon2$` prefix so should be straightforward to add it. Implement `class HtAuth::Argon2 < Algorithm; ... `  -- I don't think there's a need for `htauth-argon`- we can raise an error if the argon2 library isn't loaded and give a nice error message to folks. saying:  "Argon2 is supported, please add `gem 'argon2' to your Gemfile and try again`"

I should do an update to htauth for ruby 3.3 too make sure its in the CI pipeline for it, so happy to take a run at this shortly unless you want to do a PR.

**Comment by copiousfreetime** [comment]
Actually -- take that back -- it has `valid_hash?` just like bcrypt -- so event more straightforward to implement.

**Comment by copiousfreetime** [comment]
Well - you nerd sniped me -- so working on it right now :-)

**Comment by copiousfreetime** [comment]
@nogweii [version 2.3.0](https://rubygems.org/gems/htauth/versions/2.3.0) pushed to rubygems with support for argon2 - give it a go and let me know how it works for you. I'd also be interested in knowing about the project you're using htauth with.
